family_tree/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('persons.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Семейное древо'
admin.site.site_title = 'Семейное древо'

persons/urls.py
from django.urls import path

from . import views


app_name = 'persons'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:person_id>/', views.get_person, name="get_person"),
]

persons/models.py
from django.db import models


class Person(models.Model):
    gender_choices = [
        ('male', 'мужской'),
        ('female', 'женский')
    ]

    month_choices = [
        (None, "неизвестен"),
        (1, "Январь"),
        (2, "Февраль"),
        (3, "Март"),
        (4, "Апрель"),
        (5, "Май"),
        (6, "Июнь"),
        (7, "Июль"),
        (8, "Август"),
        (9, "Сентябрь"),
        (10, "Октябрь"),
        (11, "Ноябрь"),
        (12, "Декабрь")
    ]

    name = models.CharField("Имя", max_length=300)
    surname = models.ForeignKey('Surname', verbose_name="Фамилия", on_delete=models.CASCADE, related_name="persons")
    ex_surnames = models.ManyToManyField('Surname', verbose_name="Прошлые фамилии", blank=True,
                                         related_name="ex_persons")
    patronymic = models.CharField("Отчество", max_length=300, null=True, blank=True)
    gender = models.CharField("Пол", max_length=10, choices=gender_choices)

    birth_location = models.ForeignKey('Location', verbose_name="Место рождения", on_delete=models.SET_NULL, null=True,
                                       blank=True, related_name='persons_born')
    year_of_birth = models.IntegerField("Год рождения", null=True, blank=True)
    month_of_birth = models.PositiveSmallIntegerField("Месяц рождения", choices=month_choices, null=True, blank=True)
    day_of_birth = models.PositiveSmallIntegerField("День рождения", null=True, blank=True)

    burial_location = models.ForeignKey('Location', verbose_name="Место захоронения", on_delete=models.SET_NULL,
                                        null=True, blank=True, related_name='persons_buried')
    year_of_death = models.IntegerField("Год смерти", null=True, blank=True)
    month_of_death = models.PositiveSmallIntegerField("Месяц смерти", choices=month_choices, null=True, blank=True)
    day_of_death = models.PositiveSmallIntegerField("День смерти", null=True, blank=True)

    living_locations = models.ManyToManyField('Location', verbose_name="Места жительства", blank=True,
                                              related_name='persons_living')

    additional_information = models.TextField("Дополнительная информация", null=True, blank=True)

    mother = models.ForeignKey('Person', verbose_name="Мать", on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='kids_mother')
    father = models.ForeignKey('Person', verbose_name="Отец", on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='kids_father')
    spouse = models.ForeignKey('self', verbose_name="Супруг(-а)", on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='spouse_reverse')
    ex_spouses = models.ManyToManyField('Person', symmetrical=True, verbose_name="Бывшие супруги", blank=True,
                                        related_name='ex_spouses_reverse')

    photo = models.ImageField("Фото", upload_to="persons/", null=True, blank=True)

    creation_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Персона"
        verbose_name_plural = "Персоны"

    def get_kids(self):
        return (*self.kids_mother.all(), *self.kids_father.all())

    def __str__(self):
        full_name = ""
        if self.gender == "male":
            full_name += self.surname.male_form
        else:
            full_name += self.surname.female_form
        full_name += " " + self.name
        if self.patronymic is not None:
            full_name += " " + self.patronymic

        return full_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.spouse is not None:
            spouse_person = Person.objects.get(pk=self.spouse.id)
            if spouse_person.spouse != self:
                spouse_person.spouse = self
                spouse_person.save()
        else:
            try:
                spouse_person = Person.objects.get(spouse=self)
                spouse_person.spouse = None
                spouse_person.save()
            except Exception:
                pass


class Location(models.Model):
    name = models.CharField("Название", max_length=500, unique=True)
    description = models.TextField("Описание", null=True, blank=True)

    class Meta:
        verbose_name = "Локация"
        verbose_name_plural = "Локации"

    def __str__(self):
        return self.name


class Surname(models.Model):
    male_form = models.CharField("Мужская форма", max_length=300)
    female_form = models.CharField("Женская форма", max_length=300)

    class Meta:
        verbose_name = "Фамилия"
        verbose_name_plural = "Фамилии"

    def __str__(self):
        return f"{self.male_form} / {self.female_form}"

persons/forms.py
from django.forms import ModelForm, Select, TextInput

from .models import Person


class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['name',
                  'surname',
                  'patronymic',
                  'gender',

                  'photo',

                  'birth_location',
                  'year_of_birth',
                  'month_of_birth',
                  'day_of_birth',

                  'burial_location',
                  'year_of_death',
                  'month_of_death',
                  'day_of_death',

                  'spouse',
                  'mother',
                  'father',

                  'additional_information',
                  'living_locations',
                  'ex_spouses',
                  'ex_surnames'
                  ]
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'surname': Select(attrs={'class': 'form-control'}),
            'patronymic': TextInput(attrs={'class': 'form-control'}),
            'spouse': Select(attrs={'class': 'form-control'})
        }

persons/views.py
from django.shortcuts import render, redirect

from .models import Person
from .forms import PersonForm


def index(request):
    persons = Person.objects.all()
    context = {
        'persons': persons
    }
    return render(request, 'index.html', context)


def get_person(request, person_id):
    person = Person.objects.get(id=person_id)
    context = {
        'person': person
    }
    return render(request, 'person.html', context)


def add_person(request):
    if request.method != 'POST':
        form = PersonForm()
    else:
        form = PersonForm(data=request.POST)
        if form.is_valid():
            person = form.save(commit=False)
            person.save()
            if person.spouse is not None:
                spouse = Person.objects.get(pk=person.spouse.id)
                spouse.spouse = person
                spouse.save()
            return redirect('persons:index')

    context = {'form': form}
    return render(request, 'add_person.html', context)

persons/templates/add_person.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'persons:add_person' %}" method="post">
        {{ form.non_field_errors }}
        {% csrf_token %}
        <div class="from-group row">

            {{ form.name }}
            {{ form.surname }}
            {{ form.patronymic }}
        </div>
        <div class="form-group">
            {{ form.spouse }}
        </div>

        <button name="submit" class="btn btn-primary">add person</button>
    </form>
{% endblock content %}

persons/templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Family Trees</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
<nav class="navbar navbar-dark bg-dark">Family Tree</nav>
<div class="container pt-3">

    {% block content %}{% endblock content %}
</div>

</body>
</html>

persons/templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% for person in persons %}
        <p><a href="{% url 'persons:get_person' person.id %}">{{ person }}</a></p>
    {% empty %}
        <p>no persons here</p>
    {% endfor %}
{% endblock content %}

persons/templates/person.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'persons:index' %}"><<< назад</a>
<br>{{ person }}
<br>
{% if person.spouse %}<br>Супруг(-а): <a href="{% url 'persons:get_person' person.spouse.id %}">{{ person.spouse }}</a>{% endif %}
{% if person.mother %}<br>Мать: <a href="{% url 'persons:get_person' person.mother.id %}">{{ person.mother }}</a>{% endif %}
{% if person.father %}<br>Отец: <a href="{% url 'persons:get_person' person.father.id %}">{{ person.father }}</a>{% endif %}
<br>
{% if person.get_kids %}
<br>Дети:
<ul>
    {% for child in person.get_kids %}
    <a href="{% url 'persons:get_person' child.id %}">{{ child }}</a>
    {% endfor %}
</ul>
{% endif %}
{% endblock content %}